### ISSUE TITLE
Obscure qQCReport error

### ISSUE THREAD

**Issue by skiaphrene** [fmicompbio/QuasR#38]
Dear QuasR team,

Please see below for the obscure error that qQCReport threw:
<img width="687" alt="Screenshot 2023-06-02 at 20 57 42" src="https://github.com/fmicompbio/QuasR/assets/16306771/d71a3e29-d986-4240-8f9b-518e30bd5218">

The PDF was still generated, it just stopped after the mapping rate barplots.

For reference, here is what is returned by the qProject object:
<img width="463" alt="Screenshot 2023-06-02 at 21 00 32" src="https://github.com/fmicompbio/QuasR/assets/16306771/951d9b39-77be-45b5-bfca-ed6d214672f8">
<img width="1465" alt="Screenshot 2023-06-02 at 21 00 40" src="https://github.com/fmicompbio/QuasR/assets/16306771/3a7e9745-c104-4088-88ba-30c22cff45bb">
<img width="1330" alt="Screenshot 2023-06-02 at 21 00 47" src="https://github.com/fmicompbio/QuasR/assets/16306771/834772fc-819d-4734-9493-1960691d6031">

It is possible that the error is generated by the terrible FASTQ filenames, though as shown by the partial PDF, it was not an issue for previous plots.

If needed, FMI developers can find the qProject object in this file:
`/tungstenfs/scratch/ggrossha/smitalex/RProjects/methstep/modENCODE_L3_histone_marks/RDATA/proj.RData`

And the partial QC PDF here:
`/tungstenfs/scratch/ggrossha/smitalex/RProjects/methstep/modENCODE_L3_histone_marks/OUTPUT/qc_report.pdf`

Thank you for your time and help!

Best regards,

-- Alex

**Comment by csoneson** [comment]
This looks like a bug to me - I don't have permission to read your files, but I can reproduce the error with a small example with very long file names (that need to be truncated). I believe the reason that it works for other plot types is that there, the file names are being truncated one by one rather than in a vectorized way. I have opened a PR that I think fixes it here: #39
